### ISSUE TITLE
Issue with some of the tools menu backgrounds, and tab toolbar.

### ISSUE THREAD

**Issue by kanishkamisra** [rileytwo/darkstudio#1]
Hi

My RStudio version is 1.2.1114, and My editor theme is tomorrow night 80s with the Modern RStudio theme. I changed the css and index.htm files as follows:

Some Screenshots:

![image](https://user-images.githubusercontent.com/10777197/49125363-d86af980-f28d-11e8-82f7-607b4e9a6c85.png)

^ this one has issues with menu backgrounds

![image](https://user-images.githubusercontent.com/10777197/49125372-e3258e80-f28d-11e8-9734-62a78970cd8a.png)

^ if you look at the top right of the image, you'll see the remnants of the old modern dark blue theme.

I am using this RStudio on an Ubuntu Machine (16.08)

**Comment by rileytwo** [comment]
Hi,

Thanks for creating an issue. Since I don't have anything that's running Ubuntu 16.04, I'll need to ask some questions, and may need some more screenshots!

First thing's first: have you tried switching Editor themes, or changing the RStudio theme?

**Comment by kanishkamisra** [comment]
Yes, the problem persists in all dark themes!

**Comment by rileytwo** [comment]
Okay. I may have to ask you to do a few things for me, since I can't manually check it on a Linux.

Have you used RStudio's Developer tools? If you right click anywhere in the IDE you'll see an "Inspect Element" action in the context menu. If you click it, a window will appear with html/css elements to select and edit. From here, you can narrow down which element is causing the error. Once you find the buggy element, copy and paste the element name (it may be something weird, like .GZFAELOPZ or something) into custom_style.css file and then edit the background or and/or color properties.

If you can't figure out how to change the element on your own, comment back and put the element's name (again, may be weird like .GZFAELOPZ) in the post and I'll add it to the code so you can download the css file again.

If none of this makes sense, let me know also and I'll try to fix it :)

**Comment by kanishkamisra** [comment]
I can't seem to do the inspect element thing. I think they disable it in preview versions because I could definitely do that in the stable ones. :(

However, I updated to the latest preview version and most of the bugs are gone and it is pretty manageable!

**Comment by rileytwo** [comment]
Yeah, I’ve had that problem before where I couldn’t inspect element anywhere. I stopped using preview until they had that available, since I’m very picky and adamant about making my IDE look how I want it to.

But I’m glad the updates worked. That’s great news! I’m glad it worked out :)

If you have the problem again, let’s try and coordinate a Skype call so I can see the problem and do a hands on check.
