### ISSUE TITLE
Problem with RStudio Preview 

### ISSUE THREAD

**Issue by BerriJ** [rileytwo/darkstudio#2]
Hi,

it seems that there is a problem in RStudio v1.2.1194-1 Preview on Linux devices. I used the updated index and custom_styles.css but i still have one blue bar at the top.

Maybe you have some advice on how i can fix that.

![image](https://user-images.githubusercontent.com/37799358/50287114-ce3db480-0461-11e9-878b-91fdfa95c480.png)

Thanks so much!

**Comment by rileytwo** [comment]
Wow, I'm sorry for getting to this so late. I haven't spent much time working on this (not there is much *to* do, honestly).

I use the custom styling on both MacOS Mojave and Windows 10. On Windows, I have a similar issue, although I'm unsure of how I can change that. The menu bar seems to be out of the "Inspect Element"'s context, so I'm not aware of how to make any changes to that item specifically.

My only suggestion is to try RStudio's Dev Tools out by right clicking anywhere on the screen with RStudio open and click "Inspect Element" in the menu. I have an old MacBook Air that's running Ubuntu 18.04, but I haven't installed RStudio on it, although I plan to now that I'm seeing people use this on Linux machines.

Let me know if you have any updates since you created this issue.

**Comment by BerriJ** [comment]
Hi Riley,
thanks for responding. I'm currently moving away from R-Studio to Atom so i'm not longer in need for the theme.
As soon as I'll go back to R-Studio I'll try and let you know!
